#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Oshi Lab.
"""Regenerates vectors/omp-v1.json from the Python reference codec, and refuses to write it unless every
vector equals the bytes printed in spec/IMPLEMENTING.md and spec/TRANSPORTS.md."""

import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "python"))
from oshi_omp import omp, wire  # noqa: E402

MSG, ORIGIN, DEST, GW = 0xDEADBEEF, 0x12345678, 0x9ABCDEF0, 0x0A0B0C0D
HELLO = b"\x01hello"


def h(s):
    return bytes.fromhex(s.replace(" ", ""))


def check(name, got, expected_hex):
    exp = h(expected_hex)
    if got != exp:
        sys.exit(f"{name}: codec gives {got.hex()}, spec says {exp.hex()}")
    return got.hex()


frames = {}
frames["V1_data_custody_ok"] = check("V1", omp.DataFrame(MSG, ORIGIN, DEST, 0, 1, omp.FLAG_CUSTODY_OK, HELLO).encode(),
                                     "4f5311efbeadde78563412f0debc9a00010101 68656c6c6f")
frames["V2_data_from_phone"] = check("V2", omp.DataFrame(MSG, 0, DEST, 0, 1, omp.FLAG_CUSTODY_OK, HELLO).encode(),
                                     "4f5311efbeadde00000000f0debc9a00010101 68656c6c6f")
frames["V3_data_broadcast"] = check("V3", omp.DataFrame(MSG, ORIGIN, omp.DEST_BROADCAST, 0, 1, 0, HELLO).encode(),
                                    "4f5311efbeadde78563412ffffffff00010001 68656c6c6f")
frames["V3_internet_header"] = check("V3i", omp.DataFrame(MSG, ORIGIN, omp.DEST_INTERNET, 0, 1, 0, b"").encode(),
                                     "4f5311efbeadde78563412f0ffffff000100")
body400 = bytes(i & 0xFF for i in range(400))
v4 = omp.fragment(MSG, ORIGIN, DEST, body400)
v4_frames = [f.encode().hex() for f in v4]
for i, f in enumerate(v4):
    check(f"V4[{i}]", f.encode()[:18], f"4f5311efbeadde78563412f0debc9a{i:02x}0300")
assert [len(f.encode()) for f in v4] == [200, 200, 54]
frames["V5_sack_missing_2_9"] = check("V5", omp.SackFrame(MSG, ORIGIN, 12, 0x0DFB).encode(),
                                      "4f5312efbeadde785634120cfb0d000000000000")
frames["V5_sack_complete"] = check("V5c", omp.SackFrame(MSG, ORIGIN, 12, omp.full_bitmap(12)).encode(),
                                   "4f5312efbeadde785634120cff0f000000000000")
frames["V6_custody"] = check("V6c", omp.NoticeFrame(omp.FrameType.CUSTODY, MSG, ORIGIN, DEST).encode(),
                             "4f5313efbeadde78563412f0debc9a")
frames["V6_receipt"] = check("V6r", omp.NoticeFrame(omp.FrameType.RECEIPT, MSG, ORIGIN, DEST).encode(),
                             "4f5314efbeadde78563412f0debc9a")
frames["V7_beacon"] = check("V7", omp.BeaconFrame(omp.CAP_CUSTODIAN | omp.CAP_GATEWAY_ONLINE, 0x0100, 32).encode(),
                            "4f5315 03 0001 20")
frames["V7_probe"] = check("V7p", omp.BeaconFrame(0, 0, 0).encode(), "4f5315 00 0000 00")
frames["V8_status_delivered"] = check("V8", omp.StatusFrame(MSG, omp.DELIVERED, DEST).encode(),
                                      "4f5316efbeadde03f0debc9a")
frames["V9_pull"] = check("V9", omp.PullFrame(ORIGIN, 41, 1790000000, b"\xaa" * 64).encode(),
                          "4f5317 78563412 29000000 803bb16a" + "aa" * 64)
pull_signed = check("V9s", omp.pull_signed_bytes(ORIGIN, 1790000000, GW, 41),
                    "78563412 803bb16a 3155504f 0d0c0b0a 29000000")

bodies = {
    "raw": {"payload": b'{"t":"hi"}'.hex(),
            "body": check("V10r", omp.encode_body(b'{"t":"hi"}'), "017b2274223a226869227d")},
    "deflate": {"payload": b'{"t":"hello hello hello hello"}'.hex(),
                "body": check("V10d", omp.encode_body(b'{"t":"hello hello hello hello"}'),
                              "02ab562a51b252ca48cdc9c957c020956a01")},
}

ob_frame = bytes(i & 0xFF for i in range(200))
ob = wire.split(ob_frame, 0x11223344, 7)
check("OB[0]", ob[0][:12], "4f4210443322110702000102")
check("OB[1]", ob[1][:12], "4f4210443322110712979899")
assert [len(d) for d in ob] == [160, 58]

psk = hashlib.sha256(b"OSHI Mesh channel v1").hexdigest()
assert psk == "29436d19af55bd4e20247323c8ff455786f003119817e16cf7df3003684cb950"
secret = hashlib.sha256(b"#oshi-bridge").digest()[:16].hex()
assert secret == "485a8d4bcd50fd075ea87d7ee19f4135"

out = {
    "version": 1,
    "note": "Generated by tools/make_vectors.py from the Python reference codec and checked against the spec.",
    "values": {"msgId": MSG, "origin": ORIGIN, "dest": DEST, "gateway": GW},
    "constants": {"portnum": 256, "meshtastic_channel": "OSHI", "meshtastic_psk": psk,
                  "meshcore_channel": "#oshi-bridge",
                  "meshcore_secret": secret, "meshcore_data_type": 0xFF4F,
                  "max_frame": omp.MAX_FRAME, "data_header": omp.DATA_HEADER, "max_frag_data": omp.MAX_FRAG_DATA,
                  "max_frags": omp.MAX_FRAGS, "dest_broadcast": omp.DEST_BROADCAST, "dest_internet": omp.DEST_INTERNET},
    "frames": frames,
    "fragmentation": {"body": body400.hex(), "frames": v4_frames,
                      "counts": {"0": 1, "182": 1, "183": 2, "11648": 64}},
    "pull_signed_bytes": pull_signed,
    "bodies": bodies,
    "ob_envelope": {"frame": ob_frame.hex(), "sender": 0x11223344, "seq": 7, "datagrams": [d.hex() for d in ob]},
}
os.makedirs(os.path.join(ROOT, "vectors"), exist_ok=True)
with open(os.path.join(ROOT, "vectors", "omp-v1.json"), "w") as f:
    json.dump(out, f, indent=2)
    f.write("\n")
with open(os.path.join(ROOT, "c", "test", "vectors.h"), "w") as f:
    f.write("// Generated by tools/make_vectors.py from vectors/omp-v1.json. Do not edit.\n#pragma once\n\n")
    for k, v in frames.items():
        f.write(f'static const char *VEC_{k.upper()} = "{v}";\n')
    f.write(f'static const char *VEC_PULL_SIGNED = "{pull_signed}";\n')
    for i, v in enumerate(v4_frames):
        f.write(f'static const char *VEC_FRAG_{i} = "{v}";\n')
print("vectors/omp-v1.json and c/test/vectors.h: all vectors match the spec")
